/****** Object:  View [edw].[vw_RebateExt]    Script Date: 11-08-2025 14:45:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  View [edw].[vw_RebateExt]    Script Date: 3/26/2025 9:37:52 PM ******/
/****** Object:  View [edw].[vw_RebateExt]    Script Date: 3/26/2025 9:18:14 PM ******/
/****** Object:  View [edw].[vw_RebateExt]    Script Date: 3/08/2024 12:18:17 AM ******/
/****** Object:  View [edw].[vw_RebateExt]    Script Date: 2/08/2024 6:29:18 PM ******/
CREATE             VIEW [edw].[vw_RebateExt] 
AS 

-- BSD-171743 MB '2022-12-01' Bug fix Cutover to new code for BAU & BNZ Rebates
--			  RR 20240802 BDE, BFR and BUK moved to new rebates module in D365 from July 2024. Applying Fix.
-- BSD-332747 RR 2025027  BMX included from the new rebates module
-- v1.4	20250324 RR BSD-339194	With AzureSynapseLink the LEGALENTITYID in LedgerTable is blank, switching to Name column

WITH BRETAMRebateDealCTE AS 
(
	SELECT		DISTINCT
				T7.REFRECID 								AS [AVASALESINVOICELINERECID]
				,T7.REFCOMPANYID + T7.ITEMID + T10.SALESID 	AS SalesOrderKey
				,T7.CURRENCYCODE 							AS CURRENCYCODE
				,T7.REBATEREFACCOUNT 						AS CUSTOMERACCOUNTNUMBER
				,'' 										AS [SALESORDERLINEINVENTORYLOTID]
				,T7.ITEMID									AS ITEMNUMBER
				,'' 										AS MAINACCOUNT
				,T7.POSTINGAMOUNT 							AS [CORRECTEDREBATEAMOUNT]
				,T10.CUSTOMERREF 							AS CUSTOMERSORDERREFERENCE				
				,T7.REBATEREFDATE 							AS REBATEADJUSTMENTDATE
				,T1.DEAL 									AS REBATEID				
				,T1.STATUSID 								AS REBATESTATUS
				,T1.REBATETYPE 								AS SALESREBATEPROGRAMTYPEID
				,T7.REBATEREFDATE 							AS REBATECALCULATIONDATE
				,T10.SALESID 								AS SALESORDERNUMBER
				,T7.REBATEREFID 							AS SALESINVOICENUMBER
				,T7.REFCOMPANYID 							AS [DATAAREAID]
				,T1.[datalakemodified_datetime]				AS [SYNCSTARTDATETIME]
				,T7.REBATEREFDATE 							AS [AVAMODIFIEDDATETIME]
				,T7.REBATEREFDATE				
				,T6.JOURNALNUM
				,T7.REBATETRANSID
	FROM		[D365_DL].[dbo].TAMRebateDeal 	AS T1 
	LEFT JOIN 	[D365_DL].[dbo].TAMRebateTable 	AS T2
			ON 	T1.RECID = T2.REBATEDEAL
	LEFT JOIN 	[D365_DL].[dbo].TAMRebateDateTrans 	AS T4 
			ON 	T2.REBATEDEAL = T4.REBATEDEAL
			AND T4.REBATEPOSTED = 1
			AND T4.REBATETRANSACTIONTYPE = 0
	LEFT JOIN 	[D365_DL].[dbo].LedgerJournalTable AS T6 
			ON 	T4.REFCOMPANYID = T6.DATAAREAID
			AND T4.REFTABLEID = 1099
			AND T4.REFRECID = T6.RECID
	LEFT JOIN 	[D365_DL].[dbo].TAMRebateTrans 		AS T7 
			ON	T4.REBATETRANSID = T7.REBATETRANSID
			AND T4.REFCOMPANYID = T7.REFCOMPANYID
	INNER JOIN 	[D365_DL].[dbo].CustInvoiceJour 	AS T9 
			ON 	T7.REBATEREFID = T9.INVOICEID
	LEFT JOIN 	[D365_DL].[dbo].SalesTable AS T10
			ON	T9.SALESID = T10.SALESID
			AND	T9.DATAAREAID = T10.DATAAREAID
)
,LedgerCTE AS
(
	SELECT	 	
				--T2.dataarea 				AS LEGALENTITYID		--20250324 RR BSD-339194
				T1.NAME						AS LEGALENTITYID
			 	,t1.accountingcurrency     	AS ACCOUNTINGCURRENCY	
	FROM 		[D365_DL].dbo.Ledger T1
	LEFT JOIN 	[D365_DL].dbo.DirPartyTable T2
			ON  T1.primaryforlegalentity = T2.recid
			AND T1.partition 	= T2.partition
			AND T2.instancerelationtype 	IN (5843)
	WHERE		1=1
	--AND			ISNULL(T2.dataarea, '') > ''		--20250324 RR BSD-339194
	AND			ISNULL(T1.NAME, '') > ''
	AND			ISNULL(t1.accountingcurrency, '') > ''

),
GLAccountsCTE AS
(
	SELECT		Account
	FROM		[ANA_DL].[dbo].[vw_QVA_GLAccounts]				
	WHERE		Class = '2. Rebates' 
	AND			Type = '2.2 Rebates'	
	AND			Is365 = 1
)
SELECT		DISTINCT
			[AVASALESINVOICELINERECID]
			,ISNULL([SalesOrderKey], '')							AS [SalesOrderKey]
			,ISNULL(r.[CURRENCYCODE], '')							AS CURRENCYCODE
			,ISNULL([CUSTOMERACCOUNTNUMBER], '')					AS CUSTOMERACCOUNTNUMBER
			,ISNULL([SALESORDERLINEINVENTORYLOTID], '')				AS SALESORDERLINEINVENTORYLOTID
			,ISNULL([ITEMNUMBER], '')								AS ITEMNUMBER
			,ISNULL(r.[MAINACCOUNT], '')							AS MAINACCOUNT
			,[CORRECTEDREBATEAMOUNT]
			,ISNULL([CUSTOMERSORDERREFERENCE], '') 					AS [CUSTOMERSORDERREFERENCE]
			,T2.[ACCOUNTINGDATE]
			,[REBATEADJUSTMENTDATE]
			,ISNULL([REBATEID], '')									AS REBATEID
			,ISNULL(T8.VOUCHER, '') 								AS VOUCHERNUMBER
			,ISNULL([REBATESTATUS], '')								AS REBATESTATUS
			,[SALESREBATEPROGRAMTYPEID]
			,[REBATECALCULATIONDATE]
			,ISNULL([SALESORDERNUMBER], '')							AS SALESORDERNUMBER
			,ISNULL([SALESINVOICENUMBER], '')						AS SALESINVOICENUMBER
			,ISNULL(r.[DATAAREAID], '')								AS DATAAREAID
			,[SYNCSTARTDATETIME]
			,[AVAMODIFIEDDATETIME]
FROM 		[BRETAMRebateDealCTE] r	
LEFT JOIN 	[D365_DL].[dbo].LedgerJournalTrans AS T8 
		ON	r.JOURNALNUM = T8.JOURNALNUM 
		AND r.DATAAREAID = T8.DATAAREAID
		--AND r.REBATETRANSID = T8.DOCUMENTNUM				
LEFT JOIN 	[D365_DL].[dbo].GENERALJOURNALENTRY T2
		ON  T8.VOUCHER 	= T2.SUBLEDGERVOUCHER
INNER JOIN 	[D365_DL].[dbo].GENERALJOURNALACCOUNTENTRY T1 
		ON	T1.GENERALJOURNALENTRY  =  T2.RECID
		AND T1.PARTITION  =  T2.PARTITION
		AND T1.ISCREDIT		!=1			
WHERE 		1=1
AND 		T2.[ACCOUNTINGDATE]>='2021-12-01'
AND 		T2.[ACCOUNTINGDATE]<'2022-12-01'

UNION ALL -- BSD-171743 MB '2022-12-01' Bug fix Cutover to new code for BAU & BNZ Rebates

SELECT		DISTINCT
			[AVASALESINVOICELINERECID]
			,ISNULL([SalesOrderKey], '')							AS [SalesOrderKey]
			,ISNULL(r.[CURRENCYCODE], '')							AS CURRENCYCODE
			,ISNULL([CUSTOMERACCOUNTNUMBER], '')					AS CUSTOMERACCOUNTNUMBER
			,ISNULL([SALESORDERLINEINVENTORYLOTID], '')				AS SALESORDERLINEINVENTORYLOTID
			,ISNULL([ITEMNUMBER], '')								AS ITEMNUMBER
			,ISNULL(r.[MAINACCOUNT], '')							AS MAINACCOUNT
			,[CORRECTEDREBATEAMOUNT]
			,ISNULL([CUSTOMERSORDERREFERENCE], '') 					AS [CUSTOMERSORDERREFERENCE]
			,T2.[ACCOUNTINGDATE]
			,[REBATEADJUSTMENTDATE]
			,ISNULL([REBATEID], '')									AS REBATEID
			,ISNULL(T8.VOUCHER, '') 								AS VOUCHERNUMBER
			,ISNULL([REBATESTATUS], '')								AS REBATESTATUS
			,[SALESREBATEPROGRAMTYPEID]
			,[REBATECALCULATIONDATE]
			,ISNULL([SALESORDERNUMBER], '')							AS SALESORDERNUMBER
			,ISNULL([SALESINVOICENUMBER], '')						AS SALESINVOICENUMBER
			,ISNULL(r.[DATAAREAID], '')								AS DATAAREAID
			,[SYNCSTARTDATETIME]
			,[AVAMODIFIEDDATETIME]
FROM 		[BRETAMRebateDealCTE] r 				
LEFT JOIN 	[D365_DL].[dbo].LedgerJournalTrans AS T8 
		ON	r.JOURNALNUM = T8.JOURNALNUM 
		AND r.DATAAREAID = T8.DATAAREAID
		AND r.REBATETRANSID = T8.DOCUMENTNUM
LEFT JOIN 	[D365_DL].[dbo].GENERALJOURNALENTRY T2
		ON 	T8.VOUCHER = T2.SUBLEDGERVOUCHER
INNER JOIN 	[D365_DL].[dbo].GENERALJOURNALACCOUNTENTRY T1 
		ON	T1.GENERALJOURNALENTRY  =  T2.RECID
		AND T1.PARTITION  =  T2.PARTITION
		AND T1.ISCREDIT		!=1			
WHERE 		1=1
AND 		T8.AMOUNTCURCREDIT !=0
AND 		T2.[ACCOUNTINGDATE]>='2022-12-01'
AND			UPPER(r.DATAAREAID)	IN ('BIT', 'BAU', 'BNZ', 'BMX') --RR 20240802 Existing BU logic to be retained.


UNION ALL --RR 20240802 BDE, BFR and BUK moved to new rebates module in D365 from July 2024. Applying Fix.

SELECT		DISTINCT
			[AVASALESINVOICELINERECID]
			,ISNULL([SalesOrderKey], '')							AS [SalesOrderKey]
			,ISNULL(r.[CURRENCYCODE], '')							AS CURRENCYCODE
			,ISNULL([CUSTOMERACCOUNTNUMBER], '')					AS CUSTOMERACCOUNTNUMBER
			,ISNULL([SALESORDERLINEINVENTORYLOTID], '')				AS SALESORDERLINEINVENTORYLOTID
			,ISNULL([ITEMNUMBER], '')								AS ITEMNUMBER
			,ISNULL(r.[MAINACCOUNT], '')							AS MAINACCOUNT
			--,[CORRECTEDREBATEAMOUNT]
			,CORRECTEDREBATEAMOUNT = 								CASE 	--WHEN	ISNULL(r.DATAAREAID, '') NOT IN ('BHK') AND  r.REBATEREFDATE >= '20240701' AND
																				--	UPPER(LTRIM(RTRIM(ISNULL(r.CURRENCYCODE, '')))) <> UPPER(LTRIM(RTRIM(ISNULL(ACCOUNTINGCURRENCY, '')))) 
																			WHEN	UPPER(LTRIM(RTRIM(ISNULL(TRANSACTIONCURRENCYCODE, '')))) <> UPPER(LTRIM(RTRIM(ISNULL(ACCOUNTINGCURRENCY, '')))) 
																			--THEN 	ISNULL(T1.ACCOUNTINGCURRENCYAMOUNT, 0) 
																			THEN	ROUND(ISNULL(r.CORRECTEDREBATEAMOUNT, 0) / ISNULL (E.RATE, 1), 2)
																			ELSE	ISNULL(r.CORRECTEDREBATEAMOUNT, 0) END
			,ISNULL([CUSTOMERSORDERREFERENCE], '') 					AS [CUSTOMERSORDERREFERENCE]
			,T2.[ACCOUNTINGDATE]
			,[REBATEADJUSTMENTDATE]
			,ISNULL([REBATEID], '')									AS REBATEID
			,ISNULL(T8.VOUCHER, '') 								AS VOUCHERNUMBER
			,ISNULL([REBATESTATUS], '')								AS REBATESTATUS
			,[SALESREBATEPROGRAMTYPEID]
			,[REBATECALCULATIONDATE]
			,ISNULL([SALESORDERNUMBER], '')							AS SALESORDERNUMBER
			,ISNULL([SALESINVOICENUMBER], '')						AS SALESINVOICENUMBER
			,ISNULL(r.[DATAAREAID], '')								AS DATAAREAID
			,[SYNCSTARTDATETIME]
			,[AVAMODIFIEDDATETIME]
FROM 		[BRETAMRebateDealCTE] r 				
LEFT JOIN 	[D365_DL].[dbo].LedgerJournalTrans AS T8 
		ON	r.JOURNALNUM = T8.JOURNALNUM 
		AND r.DATAAREAID = T8.DATAAREAID
		AND r.REBATETRANSID = T8.DOCUMENTNUM
LEFT JOIN 	[D365_DL].[dbo].GENERALJOURNALENTRY T2
		ON 	T8.VOUCHER = T2.SUBLEDGERVOUCHER
INNER JOIN 	[D365_DL].[dbo].GENERALJOURNALACCOUNTENTRY T1 
		ON	T1.GENERALJOURNALENTRY  =  T2.RECID
		AND T1.PARTITION  =  T2.PARTITION
		--AND T1.ISCREDIT		!=1	
INNER JOIN	LedgerCTE T10
		ON	r.dataareaid					= T10.LEGALENTITYID					
LEFT JOIN	[edw].[vw_ExchangeRate]		E
		ON	E.FROMCURRENCY			= T10.ACCOUNTINGCURRENCY
		AND E.TOCURRENCY			= T1.TRANSACTIONCURRENCYCODE
		AND E.STARTDATE				= DATEADD(d, -1, T2.[ACCOUNTINGDATE])
WHERE 		1=1
AND 		T8.AMOUNTCURCREDIT !=0
AND			T1.LedgerAccount				IN (SELECT Account from GLAccountsCTE)
AND 		T2.[ACCOUNTINGDATE]	>='2024-07-01'
AND			UPPER(r.DATAAREAID)	IN ('BDE', 'BUK', 'BFR')
AND 		CASE 
			WHEN UPPER(r.dataareaid) = 'BUK' AND UPPER(r.REBATESTATUS) NOT IN ('NES-CONTR-UNCOND') THEN 1
			WHEN UPPER(r.dataareaid) <> 'BUK' THEN 1
			ELSE 0
			END = 1	
			
GO
